# Generated by Django 3.2.4 on 2021-09-14 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0003_dict'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temp_dict', models.JSONField()),
            ],
        ),
    ]
