# Generated by Django 3.2.4 on 2021-09-14 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0004_tempd'),
    ]

    operations = [
        migrations.CreateModel(
            name='Idf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idf_dict', models.JSONField()),
            ],
        ),
    ]
